### ISSUE TITLE
missing model

### ISSUE THREAD

**Issue by krywenko** [invite-frey/wvc-inverter#1]
hi there  when trying add inverter  ID
for wvc1200 and using  inverter id  example -- cb98   all I get is  missing model
also where does one place the modem ID
it is to bad you used mongodb  , I was hoping to install  this on a pi  but mongodb  longer supported since jessie ..  so I am  trying on a   nano 64bit computer instead  but I f i can get it to work on the nano I will try to adapt it to  use influxdb instead

**Comment by burner-** [comment]
that missing model/inverter id is caused by missing mongo connection. flow will automatically search and find modem ID so you do not need insert it via ui. After mongo connection is ok that ui works much better.

**Comment by krywenko** [comment]
thank you for a reply--  but i already wrote a new  program for  wvc modems and  HC12 modules
if you were curious 
https://github.com/krywenko/WVC-Inverter-R2-R3-HC-12--and--Modem
but thank you for your software post, even though I could not get your software to work for me  it helped me understand how the inverter worked . and I wrote my own

**Comment by invite-frey** [comment]
> that missing model/inverter id is caused by missing mongo connection. flow will automatically search and find modem ID so you do not need insert it via ui. After mongo connection is ok that ui works much better. 

Yes, MongoDB is required for this flow to work properly.
